[workspace]
members = [".", "podman-api"]

[package]
name = "podman-rest-client"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/blazzy/podman-rest-client"
license = "MIT"
readme = "README.md"


[dependencies]
async-trait = "0.1.80"
hyper = { version = "^1.3.1", features = ["full"] }
hyper-util = { version = "0.1.5", features = ["client-legacy", "http1"] }
podman-api = { path="./podman-api" }
russh = "0.43.0"
russh-keys = "0.43.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
thiserror = "1.0.61"
tokio = "1.38.0"
tower-service = "0.3.2"

[dev-dependencies]
tokio-test = "0.4.4"
