name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt

    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-rdme

    - name: Format
      run: cargo fmt --check

    - name: README sync 
      run: cargo rdme --check

    - name: Build
      run: cargo build --verbose

    - name: Set up Podman
      run: |
        # sudo apt-get install -y podman
        sudo systemctl enable --now podman.socket
        sudo systemctl status podman.socket

    - name: Tests
      run: cargo test --verbose
